baseURL = 'https://annienobear.github.io'
languageCode = 'en-us'
title = 'Shirley (Hailun) Zhang | 张海伦'

[[module.imports]]
  path = "github.com/mrmierzejewski/hugo-theme-console"

[params]
  author = ['Shirley Zhang','Shirley Zhang*']
  description = 'A personal site'
#  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
    [[menu.main]]
    identifier = "CV"
    name = "CV"
    url = "/cv/"