baseURL = 'https://annienobear.github.io'
languageCode = 'en-us'
title = 'Your Site Title'

[[module.imports]]
  path = "github.com/mrmierzejewski/hugo-theme-console"

[params]
  author = 'Your Name'
  description = 'Your site description'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20