menu:
- {name: 'home', url: '/home'}
- {name: 'cats', url: '/cats'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

cats:
- {name: 'Talon', title: 'Domestic SH', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/talon.jpg', url: 'primary-investigator'}
- {name: 'Lulu', title: 'Minuet', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lulu.jpg', url: 'lab-technician'}
- {name: 'Kennen', title: 'Minuet', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/kennen.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/annienobear'}
- {icon: 'twitter', link: 'https://twitter.com/shirley43053'}
- {icon: 'instagram', link: 'https://www.instagram.com/shirleyzhang0613'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/hailun-shirley-zhang-b2512112a/'}

contacts:
- {name: 'Hailun (Shirley) Zhang', title: 'Student', department: 'Computer Science', institution: 'University of Michigan', institution_address: 'Ann Arbor, Michigan', phone: '2066696714', email: 'hailunzh@umich.edu', image: 'assets/img/contact.jpg'}
